name: Lab2 Gradle CI

on:
  push:
    paths:
      - 'lab2/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: lab2

    steps:
      - name: Checkout lab2 code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          working-directory: lab2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
