name: Lab2 Gradle CI

on:
  push:
    paths:
      - 'lab2/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x lab2/gradlew

      - name: Build with Gradle
        working-directory: lab2
        run: ./gradlew build

      - name: Run tests
        working-directory: lab2
        run: ./gradlew test

